# Generated by Django 3.2.5 on 2021-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_alter_operacao_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
