# Generated by Django 3.2.5 on 2021-07-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_alter_operacao_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='Tipo_operacao',
            new_name='tipo_operacao',
        ),
    ]
