# Generated by Django 3.2.5 on 2021-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0008_rename_tipo_operacao_operacao_tipo_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
