# Generated by Django 3.2.5 on 2021-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0009_alter_operacao_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
