# Generated by Django 3.2.5 on 2021-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0010_operacao_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
        ),
    ]
