# Generated by Django 3.2.5 on 2021-07-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0011_alter_operacao_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
