# Generated by Django 3.2.5 on 2021-07-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0012_auto_20210725_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custodia', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('administracao', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
