# Generated by Django 3.2.5 on 2021-07-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0013_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
