# Generated by Django 3.2.5 on 2021-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0014_configuracao_taxa_saque'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='administracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='operacao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
