# Generated by Django 3.2.5 on 2021-07-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0015_auto_20210724_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='administracao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='administracao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
