# Generated by Django 3.2.5 on 2021-07-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0016_auto_20210724_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='administracao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='custodia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='taxa_saque',
        ),
    ]
