# Generated by Django 3.2.5 on 2021-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0017_auto_20210724_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='administracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='operacao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='operacao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='administracao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='taxa_saque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
