# Generated by Django 3.2.5 on 2021-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0020_auto_20210725_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
