# Generated by Django 3.2.5 on 2021-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0021_auto_20210801_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='custodia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
