# Generated by Django 3.2.5 on 2021-07-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_auto_20210721_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modalidade', models.CharField(choices=[('RF', 'Renda Fixa'), ('RV', 'Renda variável'), ('C', 'Cripto')], max_length=50)),
                ('aprovado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.usuario')),
            ],
        ),
    ]
