# Generated by Django 3.2.5 on 2021-07-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_alter_ativo_modalidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ativo',
            unique_together={('nome', 'modalidade')},
        ),
    ]
